src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="`user`")
 * ORM\HasLifecycleCallbacks
 */
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];
    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\OneToMany(targetEntity=Report::class, mappedBy="user")
     */
    private $reports;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Company;

    public function __construct()
    {
        $this->reports = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }
    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }
    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @return Collection<int, Report>
     */
    public function getReports(): Collection
    {
        return $this->reports;
    }

    public function addReport(Report $report): self
    {
        if (!$this->reports->contains($report)) {
            $this->reports[] = $report;
            $report->setUserId($this);
        }

        return $this;
    }

    public function removeReport(Report $report): self
    {
        if ($this->reports->removeElement($report)) {
            // set the owning side to null (unless already changed)
            if ($report->getUserId() === $this) {
                $report->setUserId(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTime
    {
        return $this->created_at;
    }

    public function setCreatedAt()
    {
        $this->created_at = new \DateTime();


    }

    public function getCompany(): ?string
    {
        return $this->Company;
    }

    public function setCompany(?string $Company): self
    {
        $this->Company = $Company;

        return $this;
    }
    // public function __toString() {
    //     return $this->id;
    // }
}

src/Controller/Client/ClientController.php
<?php

namespace App\Controller\Client;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Component\Security\Core\Security;

class ClientController extends AbstractController
{
    #[Route('/client', name: 'client_dashboard')]
    public function index(): Response
    {
        return $this->render('client/index.html.twig', [
            'controller_name' => 'ClientController',
        ]);
    }
    #[Route('/client/account', name: 'client_account')]
    public function client_account(): Response
    {
        return $this->render('client/account.html.twig', [
            'user' => $this->getUser(),
        ]);
    }
    #[Route('/client/report', name: 'client_report')]
    public function client_report(UserRepository $userRepo): Response
    {
       dump($this->getUser()->getId());
        return $this->render('client/report.html.twig', [
            'reports' => $userRepo->find($this->getUser()->getId())->getReports(),
        ]);
    }
}

templates/client/account.html.twig
{% extends 'base.html.twig' %}

{% block title %}Report index{% endblock %}

{% block body %}

<div class="flex flex-row">

        {{ include('admin/components/navbarUser.html.twig') }}

       <div class="flex flex-col w-screen px-20">
        
            <div class="bg-white-200 flex flex-row">
                <div class="container flex items-center px-6 py-4 mx-auto overflow-y-auto whitespace-nowrap">
                    <a href="{{ path('client_dashboard') }}" class="text-gray-600 white:text-gray-200">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20" fill="currentColor">
                            <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                        </svg>
                    </a>

                    <span class="mx-5 text-gray-500 white:text-gray-300">
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                        </svg>
                    </span>

                    <a href="#" class="text-gray-600 white:text-gray-200 hover:underline">
                        My account
                    </a>
                </div>
            </div>
        

        <div class="justify-center">
                <section class="bg-white white:bg-gray-900">
                    <div class="container py-10 mx-auto">
                        <h1 class="text-3xl font-semibold text-center text-gray-800 capitalize lg:text-4xl white:text-white">Update <span class="text-blue-500">My Account</span></h1>

                        <div class=" gap-8 mt-8 w-[1000px] pl-[33%]">
                            <div class="flex flex-col items-center p-6 space-y-3 bg-gray-100 rounded-xl white:bg-gray-800 content-center">
                                <span class="inline-block p-3 text-blue-500 bg-blue-100 rounded-full white:text-white white:bg-blue-500">
                                    <svg class="w-8 h-8" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1">
                                        <g transform="scale(.04166)">
                                            <path fill="none" d="M0 0h24v24H0Z"></path>
                                            <path fill="#4E80EF" d="M13 8c0-2.21-1.79-4-4-4C6.79 4 5 5.79 5 8c0 2.21 1.79 4 4 4s4-1.79 4-4Zm2 2v2h3v3h2v-3h3v-2h-3V7h-2v3h-3ZM1 18v2h16v-2c0-2.66-5.33-4-8-4s-8 1.34-8 4Z"></path>
                                        </g>
                                    </svg>
                                </span>

                                <h1 class="text-2xl font-semibold text-gray-700 capitalize white:text-white">New User</h1>

                                
                                    

                                    <div>
                                        <label class="text-gray-700 dark:text-dark-200 " for="Lastname">EmailUser</label>
                                        <input value='{{ user.email }}' 
                                                class="'form-control  w-full px-4 py-2 mt-2 text-gray-700 bg-white border rounded-md white:bg-gray-800 white:text-gray-300 white:border-gray-600 focus:border-blue-400 white:focus:border-blue-300 focus:ring-blue-300 focus:outline-none focus:ring focus:ring-opacity-40"  disabled>    
                                    </div>

                                    <div>
                                        <label class="text-gray-700 dark:text-dark-200 " for="Lastname">Firstname</label>
                                        <input value='{{ user.firstname }}' 
                                                class="'form-control  w-full px-4 py-2 mt-2 text-gray-700 bg-white border rounded-md white:bg-gray-800 white:text-gray-300 white:border-gray-600 focus:border-blue-400 white:focus:border-blue-300 focus:ring-blue-300 focus:outline-none focus:ring focus:ring-opacity-40">    
                                    </div>

                                    <div>
                                        <label class="text-gray-700 dark:text-dark-200 " for="Lastname">Lastname</label>
                                        <input value='{{ user.username }}' 
                                                class="'form-control  w-full px-4 py-2 mt-2 text-gray-700 bg-white border rounded-md white:bg-gray-800 white:text-gray-300 white:border-gray-600 focus:border-blue-400 white:focus:border-blue-300 focus:ring-blue-300 focus:outline-none focus:ring focus:ring-opacity-40">    
                                    </div>

                                    <div>
                                        <label class="text-gray-700 dark:text-dark-200 " for="Lastname">Company</label>
                                        <input value='{{ user.company }}' 
                                                class="'form-control  w-full px-4 py-2 mt-2 text-gray-700 bg-white border rounded-md white:bg-gray-800 white:text-gray-300 white:border-gray-600 focus:border-blue-400 white:focus:border-blue-300 focus:ring-blue-300 focus:outline-none focus:ring focus:ring-opacity-40">    
                                    </div>

                                    

                                    
                                    
                            

                                    

                                    <button type="submit" class="btn w-full px-4 py-2 tracking-wide text-white transition-colors duration-200 transform bg-blue-800 rounded-md hover:bg-blue-600 focus:outline-none focus:bg-gray-600">Update</button>
                                

                                
                            </div>

                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    

{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ClientController!{% endblock %}

{% block body %}



<div class="flex flex-row">

        {{ include('admin/components/navbarUser.html.twig') }}

        <div class="flex flex-col w-screen px-20">
        </div>


        

</div>
{% endblock %}

templates/client/report.html.twig
{% extends 'base.html.twig' %}

{% block title %}Report index{% endblock %}

{% block body %}
    <div class="flex flex-row">

        {{ include('admin/components/navbarUser.html.twig') }}
        <div class="flex flex-col w-screen px-20">
            <div class="flex flex-row">
                <div class="bg-white-200 flex flex-row">
                    <div class="container flex items-center px-6 py-4 mx-auto overflow-y-auto whitespace-nowrap">
                        <a href="{{ path('client_dashboard') }}" class="text-gray-600 white:text-gray-200">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20" fill="currentColor">
                                <path d="M10.707 2.293a1 1 0 00-1.414 0l-7 7a1 1 0 001.414 1.414L4 10.414V17a1 1 0 001 1h2a1 1 0 001-1v-2a1 1 0 011-1h2a1 1 0 011 1v2a1 1 0 001 1h2a1 1 0 001-1v-6.586l.293.293a1 1 0 001.414-1.414l-7-7z" />
                            </svg>
                        </a>

                        <span class="mx-5 text-gray-500 white:text-gray-300">
                            <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20" fill="currentColor">
                                <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
                            </svg>
                        </span>

                        <a href="#" class="text-gray-600 white:text-gray-200 hover:underline">
                            My Report
                        </a>
                    </div>
                </div>
            </div>

            <div class="container pt-10 mx-auto px-20">
                <div class="flex flex-row">
                    <h1 class="text-3xl w-100 font-semibold text-center text-gray-800 capitalize lg:text-4xl white:text-white ">List of <span class="text-blue-500">My Report</span></h1>
                </div>
                
                
                
                <div class="flex flex-row pt-5">
                    
                    <div>
                        <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                            <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                                <table class="min-w-full leading-normal">
                                    <thead>
                                        <tr>
                                            <th
                                                class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                                Id
                                            </th>
                                            <th
                                                class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                                Company
                                            </th>
                                            <th
                                                class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                                Product name
                                            </th>
                                            <th
                                                class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                                Creat At
                                            </th>
                                            <th
                                                class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                                Actions
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    {% for report in reports %}
                                        <tr>
                                            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                                <div class="flex items-center">
                                                    
                                                        <div>
                                                            <p class="text-gray-900 whitespace-no-wrap">
                                                                {{ report.id }}
                                                            </p>
                                                        </div>
                                                    </div>
                                            </td>
                                            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                                <p class="text-gray-900 whitespace-no-wrap">
                                                {{ report.User.Company }}
                                                </p>
                                            </td>
                                            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                                <p class="text-gray-900 whitespace-no-wrap">
                                                    {{ report.product }}
                                                </p>
                                            </td>
                                            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                                <p class="text-gray-900 whitespace-no-wrap">
                                                    {{ report.CreatedAt ? report.CreatedAt|date('Y-m-d H:i:s') : '' }}
                                                </p>
                                            </td>
                                            <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm ">
                                                <a href="{{ asset('rapport/rapport_' ~report.id~ '.pdf') }}">
                                                    <svg class="w-8 h-8" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24">
                                                        <path fill="none" d="M0 0h24v24H0V0Z"></path>
                                                        <path fill="#263FA9" d="M16.59 9H15V4c0-.55-.45-1-1-1h-4c-.55 0-1 .45-1 1v5H7.41c-.89 0-1.34 1.08-.71 1.71l4.59 4.59c.39.39 1.02.39 1.41 0l4.59-4.59c.63-.63.19-1.71-.7-1.71ZM5 19c0 .55.45 1 1 1h12c.55 0 1-.45 1-1s-.45-1-1-1H6c-.55 0-1 .45-1 1Z"></path>
                                                    </svg>
                                                </a>
                                            </td>
                                        </tr>

                                        {% else %}
                                            <tr>
                                                <td colspan="7">no records found</td>
                                            </tr>
                                        {% endfor %}        
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        </div>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}